version: '3.8'
services:
  backend-dineease: 
    image: baggaaayush05/dine-ease-backend:v1
    container_name: backend_dineease
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    # volumes: FOR BIND MOUNTING
    #   - ./backend/src:/app/src:ro

  frontend-dineease:
    image: baggaaayush05/dine-ease-frontend:v1
    container_name: frontend_dineease
    depends_on:
      - backend-dineease
    ports:
      - "5173:5173"
    # vite adds env var in build time so no need to pass here 
    # env_file:
    #   - ./frontend/DineEase/.env
    # volumes: FOR BIND MOUNTING FOR HOT RELOADS DEV MODE
    #   - ./frontend/DineEase/src:/app/src:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - backend-dineease
    