-- AlterTable
ALTER TABLE "Address" ALTER COLUMN "pincode" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Store" ALTER COLUMN "pincode" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Users" ALTER COLUMN "contactNo" SET DATA TYPE BIGINT;
